export const API_CALLS = [
  {
    id: "settingsSchemas",
    group: "settings",
    method: "GET",
    path: "/api/v2/settings/schemas?pageSize=500",
    description: "List Settings 2.0 schemas available in the tenant.",
  },
  {
    id: "activeGates",
    group: "environment",
    method: "GET",
    path: "/api/v2/activeGates",
    description: "ActiveGate inventory and online/offline details.",
  },
  {
    id: "apiTokens",
    group: "environment",
    method: "GET",
    path: "/api/v2/apiTokens?pageSize=500&fields=%2Benabled%2C%2BcreationDate%2C%2BlastUsedDate%2C%2Bscopes",
    description: "API token inventory, enabled/disabled status, and scopes.",
  },
  {
    id: "syntheticMonitors",
    group: "environment",
    method: "GET",
    path: "/api/v2/synthetic/monitors?pageSize=500",
    description: "Synthetic browser, HTTP, and NAM monitor inventory.",
  },
  {
    id: "syntheticLocations",
    group: "environment",
    method: "GET",
    path: "/api/v2/synthetic/locations?pageSize=500",
    description: "Synthetic public/private locations.",
  },
  {
    id: "networkZones",
    group: "environment",
    method: "GET",
    path: "/api/v2/networkZones?pageSize=500",
    description: "Network zone configuration inventory.",
  },
  {
    id: "slos",
    group: "environment",
    method: "GET",
    path: "/api/v2/slo?pageSize=500",
    description: "Service-level objectives from Environment API v2.",
  },
  {
    id: "extensions",
    group: "environment",
    method: "GET",
    path: "/api/v2/extensions?pageSize=100",
    description: "Extensions 2.0 inventory.",
  },
  {
    id: "credentialVault",
    group: "environment",
    method: "GET",
    path: "/api/v2/credentials?pageSize=500",
    description: "Credential vault entry inventory.",
  },
  {
    id: "problems",
    group: "environment",
    method: "GET",
    path: "/api/v2/problems?pageSize=500&from=now-7d",
    description: "Problem history for the last 7 days.",
  },
  {
    id: "attacks",
    group: "environment",
    method: "GET",
    path: "/api/v2/attacks?pageSize=500&from=now-30d",
    description: "Application security attacks for the last 30 days, when enabled.",
  },
  {
    id: "classicDashboards",
    group: "classic-config",
    method: "GET",
    path: "/api/config/v1/dashboards?pageSize=500",
    description: "Classic dashboard inventory.",
  },
  {
    id: "grailDashboards",
    group: "documents",
    method: "GET",
    path: "/platform/document/v1/documents?filter=type%3D%3D'dashboard'&pageSize=1",
    description: "Grail dashboard document count. Usually requires OAuth/platform bearer token.",
  },
  {
    id: "notebooks",
    group: "documents",
    method: "GET",
    path: "/platform/document/v1/documents?filter=type%3D%3D'notebook'&pageSize=1",
    description: "Notebook document count. Usually requires OAuth/platform bearer token.",
  },
  {
    id: "documentShares",
    group: "documents",
    method: "GET",
    path: "/platform/document/v1/environment-shares?pageSize=1",
    description: "Shared document count. Usually requires OAuth/platform bearer token.",
  },
  {
    id: "workflows",
    group: "automation",
    method: "GET",
    path: "/platform/automation/v1/workflows?limit=500",
    description: "Automation workflow inventory. Usually requires OAuth/platform bearer token.",
  },
  {
    id: "workflowExecutions",
    group: "automation",
    method: "GET",
    path: "/platform/automation/v1/executions?limit=500",
    description: "Automation execution history. Usually requires OAuth/platform bearer token.",
  },
];

export const SETTINGS_SCHEMA_IDS = [
  "builtin:alerting.profile",
  "builtin:problem.notifications",
  "builtin:anomaly-detection.metric-events",
  "builtin:alerting.maintenance-window",
  "builtin:tags.auto-tagging",
  "builtin:management-zones",
  "builtin:ownership.teams",
  "builtin:ownership.config",
  "builtin:process-group.simple-detection-rule",
  "builtin:service-detection.full-web-request",
  "builtin:logmonitoring.log-storage-settings",
  "builtin:logmonitoring.log-events",
  "builtin:rum.web.rum-javascript-updates",
  "builtin:sessionreplay.web.privacy-preferences",
  "builtin:appsec.attack-protection-settings",
  "builtin:cloud.aws",
  "builtin:cloud.azure",
  "builtin:networkzones",
  "builtin:deployment.oneagent.updates",
  "builtin:openpipeline.logs.pipelines",
  "builtin:openpipeline.metrics.pipelines",
  "builtin:monitoring.slo",
  "builtin:davis.anomaly-detectors",
  "builtin:segment",
  "builtin:declarativegrouping",
  "builtin:issue-tracking.integration",
  "builtin:reliability-guardian",
  "builtin:anomaly-detection.frequent-issues",
  "builtin:os-services-monitoring",
  "builtin:oneagent.features",
  "builtin:logmonitoring.log-custom-attributes",
  "builtin:appsec.runtime-vulnerability-detection",
  "builtin:appsec.notification-integration",
  "builtin:bizevents.http.incoming",
  "builtin:bizevents-processing-pipelines.rule",
  "builtin:bizevents-processing-metrics.rule",
  "builtin:bizevents-processing-buckets.rule",
  "builtin:calculated-metrics-service",
  "builtin:calculated-metrics-log",
  "builtin:bizevents-security-context-rules",
];

export const APP_FUNCTION_CALLS = [
  { id: "activeGates", functionName: "activeGates", method: "GET", description: "ActiveGate inventory through deployed app function." },
  { id: "attacks", functionName: "attacks", method: "GET", description: "Runtime attack inventory through deployed app function." },
  { id: "classicDashboards", functionName: "classicDashboards", method: "GET", description: "Classic dashboard inventory through deployed app function." },
  { id: "credentialVault", functionName: "credentialVault", method: "GET", description: "Credential vault inventory through deployed app function." },
  { id: "documentShares", functionName: "documentShares", method: "GET", description: "Document share summary through deployed app function." },
  { id: "extensions", functionName: "extensions", method: "GET", description: "Extensions 2.0 inventory through deployed app function." },
  { id: "metricsCheck", functionName: "metricsCheck", method: "GET", description: "Metric availability checks through deployed app function." },
  { id: "networkZones", functionName: "networkZones", method: "GET", description: "Network zone inventory through deployed app function." },
  { id: "problems", functionName: "problems", method: "GET", description: "Problem history through deployed app function." },
  { id: "releases", functionName: "releases", method: "GET", description: "Release information through deployed app function." },
  { id: "slos", functionName: "slos", method: "GET", description: "SLO inventory through deployed app function." },
  { id: "syntheticLocations", functionName: "syntheticLocations", method: "GET", description: "Synthetic locations through deployed app function." },
  { id: "tokens", functionName: "tokens", method: "GET", description: "API token inventory through deployed app function." },
  { id: "workflowExecutions", functionName: "workflowExecutions", method: "GET", description: "Workflow execution history through deployed app function." },
  {
    id: "settingsObjectsCounts",
    functionName: "settingsObjects",
    method: "POST",
    description: "Settings object counts through deployed app function.",
    body: { action: "counts" },
  },
];
