import type { ReviewAreaDefinition } from "../types/review.types";

export const REVIEW_AREAS: ReviewAreaDefinition[] = [
  {
    id: "monitoring",
    name: "Monitoring Configuration",
    shortName: "Monitoring",
    description: "OneAgent deployment, ActiveGate status, host groups, and monitoring modes",
    icon: "server",
    route: "/monitoring",
    weight: 1.0,
  },
  {
    id: "settings",
    name: "Settings Framework",
    shortName: "Settings",
    description: "Settings v1 vs Settings 2.0 adoption and configuration migration",
    icon: "settings",
    route: "/settings",
    weight: 1.0,
  },
  {
    id: "storage",
    name: "Data Storage & Grail",
    shortName: "Storage",
    description: "Grail bucket configuration, log storage, and data retention policies",
    icon: "database",
    route: "/storage",
    weight: 0.8,
  },
  {
    id: "alerting",
    name: "Alerting & Davis AI",
    shortName: "Alerting",
    description: "Metric events, Davis Analyzers, alerting profiles, and notifications",
    icon: "bell",
    route: "/alerting",
    weight: 1.0,
  },
  {
    id: "dashboards",
    name: "Dashboards & Visualization",
    shortName: "Dashboards",
    description: "Classic vs Grail dashboards, notebooks, and USQL migration",
    icon: "dashboard",
    route: "/dashboards",
    weight: 0.8,
  },
  {
    id: "extensions",
    name: "Extensions",
    shortName: "Extensions",
    description: "Extensions 1.0 vs 2.0 migration and extension health",
    icon: "plugin",
    route: "/extensions",
    weight: 0.9,
  },
  {
    id: "automation",
    name: "Automation & Workflows",
    shortName: "Automation",
    description: "Workflow adoption, classic notifications, and automation rules",
    icon: "workflow",
    route: "/automation",
    weight: 0.7,
  },
  {
    id: "tagging",
    name: "Tagging & Organization",
    shortName: "Tagging",
    description: "Auto-tagging, management zones, ownership, and entity organization",
    icon: "tag",
    route: "/tagging",
    weight: 0.8,
  },
  {
    id: "api-access",
    name: "API & Access Management",
    shortName: "API/Access",
    description: "API token inventory, OAuth adoption, and credential management",
    icon: "key",
    route: "/api-access",
    weight: 0.9,
  },
  {
    id: "security",
    name: "Security",
    shortName: "Security",
    description: "Application security, vulnerabilities, and attack detection",
    icon: "shield",
    route: "/security",
    weight: 1.0,
  },
  {
    id: "synthetic",
    name: "Synthetic Monitoring",
    shortName: "Synthetic",
    description: "Browser and HTTP monitors, locations, and execution health",
    icon: "globe",
    route: "/synthetic",
    weight: 0.7,
  },
  {
    id: "rum",
    name: "RUM & Session Replay",
    shortName: "RUM",
    description: "Real User Monitoring configuration and USQL to DQL migration",
    icon: "user",
    route: "/rum",
    weight: 0.7,
  },
  {
    id: "logs",
    name: "Log Monitoring",
    shortName: "Logging",
    description: "Classic vs Grail log ingestion, OpenPipeline, and log rules",
    icon: "document",
    route: "/logs",
    weight: 0.9,
  },
  {
    id: "metrics",
    name: "Metrics",
    shortName: "Metrics",
    description: "Custom metrics, calculated metrics, and metric event migration",
    icon: "chart",
    route: "/metrics",
    weight: 0.8,
  },
];

export const REVIEW_AREA_MAP = new Map(
  REVIEW_AREAS.map((area) => [area.id, area])
);
